### ISSUE TITLE
 Compiler error: 'EEPROMwl' was declared 'extern' and later 'static' [-fpermissive]

### ISSUE THREAD

**Issue by truglodite** [PRosenb/EEPROMWearLevel#1]
I get compiler errors when trying to compile the SimpleConfiguration.ino example using Arduino 1.8. The complete error message is pasted below:

`
C:\Users\me\Documents\Arduino\libraries\EEPROMWearLevel\EEPROMWearLevel.cpp:4:24: error: 'EEPROMwl' was declared 'extern' and later 'static' [-fpermissive]

 static EEPROMWearLevel EEPROMwl;

                        ^

In file included from C:\Users\me\Documents\Arduino\libraries\EEPROMWearLevel\EEPROMWearLevel.cpp:2:0:

C:\Users\me\Documents\Arduino\libraries\EEPROMWearLevel\EEPROMWearLevel.h:323:24: note: previous declaration of 'EEPROMwl'

 extern EEPROMWearLevel EEPROMwl;

                        ^

Using library EEPROMWearLevel at version 1.0.0 in folder: C:\Users\me\Documents\Arduino\libraries\EEPROMWearLevel 
Using library EEPROM at version 2.0 in folder: C:\Users\me\Documents\Arduino\hardware\arduino\avr\libraries\EEPROM 
exit status 1
Error compiling for board Arduino/Genuino Uno.
`

**Comment by PRosenb** [comment]
Hi @truglodite , thanks for reporting this issue. I addressed various compiler warnings and on master it should compile fine again.
