### ISSUE TITLE
How to make starting EEPROM addresses other than 0. 

### ISSUE THREAD

**Issue by asishjohney** [PRosenb/EEPROMWearLevel#11]
Thanq for your great library,

Currently am using EEPROM address from 0 to 100 for other application. How I can change the index starting address to address < 100?. Kindly give your valuable reply.

**Comment by PRosenb** [comment]
Hi @asishjohney, thanks for your input.
With the current implementation, it is not possible to change the index starting address but it's possible to enhance it for that.
Is there no way you can move your other application to a higher address range?
Cheers

**Comment by asishjohney** [comment]
ThankQ so much for your reply @PRosenb,  I will change my current application to higher address.
