### ISSUE TITLE
missing overloading (long)

### ISSUE THREAD

**Issue by avandalen** [PRosenb/EEPROMWearLevel#13]
Hi Pete

This goes wrong
EEPROMwl.put(0, 125); 

This goes well
EEPROMwl.put(0, (long)125); 

Someting with overloading?

But the rest works fine, thank you for your library..
www.avdweb.nl
Albert

**Comment by PRosenb** [comment]
Hi Albert,
`EEPROMWearLevel` extends from the EEPROM library, namely from its class `EEPROMClass` where these functions are implemented.
The code can be found [at the Arduino repo](https://github.com/arduino/ArduinoCore-avr/blob/master/libraries/EEPROM/src/EEPROM.h).
Is there something missing or is it related to the template not taking the right type if you don't specify it?
Cheers,
Pete

**Comment by avandalen** [comment]
Hi Pete

It is just that the functions do not take always automaticly the correct type
We need casts (long)  of (byte) etc. 

But don’t worry, I can work with it, no big problem. 



Have a nice day



Albert

**Comment by PRosenb** [comment]
Hi @avandalen , thanks for your reply.
Sounds good. If you happen to have an idea how it could be improved just let me know.
Have a nice day mate.
Cheers, Pete

**Comment by avandalen** [comment]
Maybe you can add an example with the cast to the examples.
EEPROMwl.put(0, (long)125);

By the way, I'm using your lib to write values to the EEPROM just before the Arduino power shut down. Quite complicated, it should also work when switching the power on and off very fast.

**Comment by PRosenb** [comment]
A good idea. Should you happen to have one feel free to create a pull request.

Wow interesting regarding using it on Arduino power shot down. I sent you an email in that regard.
