### ISSUE TITLE
Maximum number of allowed EEPROM writes?

### ISSUE THREAD

**Issue by avandalen** [PRosenb/EEPROMWearLevel#14]
Hi Pete

Can you tell what the maximum number of allowed EEPROM writes is in the examples?

**Comment by PRosenb** [comment]
Hi @avandalen 
Do you mean to add comments on how many time EEPROM writes can happen until the EEPROM wears out?
Cheers

**Comment by avandalen** [comment]
yes, this is what I want to know

**Comment by PRosenb** [comment]
I see. I haven't tested it myself but remember reading reports of tests others had done. Unfortunately I cannot find it any more.
Should you do some tests yourself or find a good reference we could add it to the readme.

**Comment by avandalen** [comment]
Hi Pete



The library can’t be simply tested, the maximum number of writes must be determined theoretically,

because the max number cycles is 100k but can be much more with an individual processor 

Can we assume that the following is correct?
The processor is ATtiny3217
is has a 256 bytes EEPROM, 100k max cycles

I use words, 
AMOUNT_OF_INDEXES = 1
The number of words = 256/4=64
The max.number of  writes = 64*100k = 6400000 ?

kind regards

Albert

**Comment by PRosenb** [comment]
Hi @avandalen , I see what you mean. Almost, because there are also some control bytes used that need to be subtracted.
See [Control Bytes](https://github.com/PRosenb/EEPROMWearLevel#control-bytes) for details. So roughly 64/8=8 to subtract.

**Comment by avandalen** [comment]
thanks a lot

**Comment by PRosenb** [comment]
You're welcome, I hope it helps you.
