### ISSUE TITLE
Kudos for your library,  it enabled my project to have an MVP for my plant-watering-system 

### ISSUE THREAD

**Issue by eddyp** [PRosenb/EEPROMWearLevel#16]
Integrating your library in my project was a breeze. 

Now I have a nice MVP, and I'll have my 0.1 release soon. 

https://youtu.be/MlZQGAmdXMs
https://youtu.be/N3DQ9_Ras7Y
https://youtu.be/6VTN1WMB9zE

Project is here: https://github.com/uCautomation/plant-watering-system/

**Comment by PRosenb** [comment]
Great to hear @eddyp , thanks for letting me know.
