### ISSUE TITLE
Generates warning about unused declaration for 'EEPROM'

### ISSUE THREAD

**Issue by eddyp** [PRosenb/EEPROMWearLevel#17]
It seems the library is declaring EEPROM but not using it. I assume this is a convenience so the project using the EEPROMWearLevel library can use EEPROM as before, but if so, it has the undesirable effect of generating a warning when not using EEPROM:

> /home/eddy/opt/arduino-1.8.13/hardware/tools/avr/bin/avr-g++ -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/eddy/opt/arduino-1.8.13/hardware/arduino/avr/cores/arduino -I/home/eddy/opt/arduino-1.8.13/hardware/arduino/avr/variants/eightanaloginputs -I/home/eddy/Arduino/libraries/Low-Power -I/home/eddy/Arduino/libraries/LiquidCrystal_PCF8574/src -I/home/eddy/opt/arduino-1.8.13/hardware/arduino/avr/libraries/Wire/src -I/home/eddy/Arduino/libraries/EEPROMWearLevel -I/home/eddy/opt/arduino-1.8.13/hardware/arduino/avr/libraries/EEPROM/src /home/eddy/Arduino/libraries/EEPROMWearLevel/EEPROMWearLevel.cpp -o /tmp/arduino_build_8835/libraries/EEPROMWearLevel/EEPROMWearLevel.cpp.o
> In file included from /home/eddy/Arduino/libraries/EEPROMWearLevel/EEPROMWearLevel.h:23:0,
>                  from /home/eddy/Arduino/libraries/EEPROMWearLevel/EEPROMWearLevel.cpp:2:
> /home/eddy/opt/arduino-1.8.13/hardware/arduino/avr/libraries/EEPROM/src/EEPROM.h:145:20: warning: 'EEPROM' defined but not used [-Wunused-variable]
>  static EEPROMClass EEPROM;
>                     ^~~~~~

As EEPROMWearLevel.cpp does not seem to use EEPROM, a simple `(void) EEPROM;` in the EEPROMWearLevel code somewhere should be enough.

Unfortunately, the user of the library also has to do this, too. But accounting for the convenience and the fact that is code controlled by the user, they can add their silencing `(void) EEPROM;` statement.

**Comment by PRosenb** [comment]
Hi @eddyp , the library does not use `EEPROM` but it uses other definitions in `EEPROM.h` (namely `EEPROMClass`). That's why it includes it in `EEPROMWearLevel.h`.
Are you suggesting to add a `(void) EEPROM;` in `EEPROMWearLevel.cpp`? I just tried that but get a compilation error.

**Comment by eddyp** [comment]
> Are you suggesting to add a `(void) EEPROM;` in `EEPROMWearLevel.cpp`? I just tried that but get a compilation error.

Yes. But that line needs to be in an executable block, as its not a declaration, like here:


https://github.com/uCautomation/plant-watering-system/blob/5674ffa646edfcd2c49138197f3c3319793f2833/water_system/WaterSystem.cpp#L102

**Comment by PRosenb** [comment]
I see. Does it have any other effect that suppressing the warning? Can EEPROM still be used by the code when doing that?

**Comment by eddyp** [comment]
Yes. It can still be used. It only silences the warning. You can try in a sketch to verify.

**Comment by PRosenb** [comment]
Nice to hear. I currently don't have access to an Arduino board.. Will need to check it out later.

**Comment by PRosenb** [comment]
I could test it now with an Arduino Uno and it looks fine so far. It's on master now, not yet in a release. Could you also give it a test?

**Comment by eddyp** [comment]
Sure. How do I use it without Arduino IDE support? Should I just hack my local copy from the IDE files?

L.E.: Hacked it to be identical to your change. Looks good on my end, too.

(Sorry, was on vacation last week)

**Comment by PRosenb** [comment]
Hi @eddyp , yes I think that's the best approach to do it that way. And afterwards delete the lib and download it again with the Arduino IDE. Many thanks for checking it out. Cheers

**Comment by eddyp** [comment]
As I said, it works. I'll leave as is. The warning is annoying me anyways, so I'll keep it like this until your official release :)
