### ISSUE TITLE
ringBuffer and INDEX_RING_BUFFER

### ISSUE THREAD

**Issue by Harry-ei6ku** [PRosenb/EEPROMWearLevel#18]
I'm running the ringBufffer example and it runs as expected...

but Im not clear on how to use the "AMOUNT_OF_INDEXES" , and  "INDEX_RING_BUFFER".

INDEX_RING_BUFFER seems to crash the example with any value above 0,

and Im not sure how to access indexes above 1 ?

Thanks

Harry

**Comment by PRosenb** [comment]
Hi @Harry-ei6ku, nice are you using my library. `AMOUNT_OF_INDEXES` defines the amount of indexes you have on your EEPROM, so you can use indexes from 0 to `AMOUNT_OF_INDEXES` - 1.
For example `AMOUNT_OF_INDEXES` == 1 you have the index 0 only, with `AMOUNT_OF_INDEXES` == 2 you have indexes 0 and 1.
The ring buffer can also be in one of the indexes but must be inside of `AMOUNT_OF_INDEXES` - 1. So if you want to use multiple ring buffers, you need to use a higher number for `AMOUNT_OF_INDEXES` than one.
