### ISSUE TITLE
Question: What happens if power gets cut while write is happening?

### ISSUE THREAD

**Issue by farbefreak** [PRosenb/EEPROMWearLevel#19]
Hello!

You can see my question above.
I am wondering what happens in the unlikely case that the write happens exactly as a brownout happens.
Will the library catch that and restore to a known good state or will all the data be corrupt? 

Will only the variable that gets written be corrupt?  If thats the case, we could fix that by storing all values three times and comparing them.

BTW: thanks for your Lib, have a nice day!

**Comment by PRosenb** [comment]
Hi @farbefreak,
Thanks for using my library.
That's an interesting question. I'm not sure what exactly happens in this case but the possibility of corrupting the EEPROM is quite low because the library uses control bits to store the last read/write location. If power gets cut during the write operation, it's likely that the bit is either fully written or not written. While writing the bit, it only writes one bit but not the whole byte the bit is in to reduce wear.
There is no logic in the library to catch this case and restore the state.

**Comment by farbefreak** [comment]
If the data gets written before the control byte, then that should be ok. 

Because a brownout would either result in the data half written but not the control bit or in data being complete but no control bit set. 

In the first case, the library would just assume that no data is present and fall back to the old location because the control bits are still set to the previous fully written location.

In the second case, the data might be fully there but the control bits would still point to the old value.

In both cases, the old fully written value would be used without a problem except the unlikely loss of a fully written dataset without the control bits being set.

So worst case: one dataset being lost with fallback to old data = no problem...

I am trying to implement a hour meter on a attiny that only need to be roughly exact. Writing every minute should work with your wear leveling algorithm. But it wouldnt work if power being lost while writing results in corrupt data.

**Comment by PRosenb** [comment]
Yes, the data gets written before the control bit in [EEPROMWearLevel.h#L310](https://github.com/PRosenb/EEPROMWearLevel/blob/0ccb128fe9f966a58ca211fb4796793033ea4dc1/src/EEPROMWearLevel.h#L310).
But when the allocated space is full and it starts again on the start, it deletes all control bits first, see [EEPROMWearLevel.cpp#L174](https://github.com/PRosenb/EEPROMWearLevel/blob/0ccb128fe9f966a58ca211fb4796793033ea4dc1/src/EEPROMWearLevel.cpp#L174).

That could be changed but would need quite a lot of retesting. Or you could check for this case with `EEPROMwl.length()` and `EEPROMwl.getCurrentIndexEEPROM()` and additionally store it at a different place when this happens.
