### ISSUE TITLE
Question on efficacy of wear leveling on control bytes

### ISSUE THREAD

**Issue by chieffancypants** [PRosenb/EEPROMWearLevel#2]
Hey there!  I don't have much experience in programming MCUs, so I may be misunderstanding the intent behind the code, but I noticed that you've created this concept of a control byte, whereby each bit is cleared one-by-one as you write new data to the index.  Because the ATmega EEPROM writes in byte-sized blocks, each time you're clearing a bit from the control byte, it counts as a full write/erase cycle for the entire cell, meaning the control bytes will wear out approximately 8 times faster than the rest of the `dataIndex` cells.

If I'm understanding this correctly, was this done as a kind of trade-off to optimize for valuable EEPROM space?  If I'm not understanding correctly, mind setting me straight?

Thanks!

**Comment by PRosenb** [comment]
Hi @chieffancypants, thanks for the question.
The first/accepted answer in this post explains it: [100k EEPROM writes “per bit” or as a whole?](https://electronics.stackexchange.com/questions/21232/100k-eeprom-writes-per-bit-or-as-a-whole)
Only clearing a byte (set all bits to 1) causes it to wear. The library minimizes that in clearing it first (set all bits in the byte to 1) and then write single bits to 0 without clearing it every time.
