### ISSUE TITLE
Description of parameters not clear

### ISSUE THREAD

**Issue by Interfix** [PRosenb/EEPROMWearLevel#3]
When declaring the int array to pass to the begin() method, is the int value meant as the size of one piece of data the partition is going to hold or the space that is being reserved for the respective partition?

Additionally: is the int value I pass to begin() supposed to include the bytes for control bytes and layoutVersion?

**Comment by PRosenb** [comment]
Hi @Interfix, thanks for your question. The size array defines the length of the partition on the `EEPROM` including control bytes so the usable data is a bit smaller. You can get the max usable data size by calling `getMaxDataLength()`. The `layoutVersion` is separately and uses only one byte at the beginning of the `EEPROM`.
I'll update the method description as follows:

`
    @param lengths array of the partition lengths to use on the EEPROM. The length includes the
    control bytes so the usable length for data is smaller. You can get the max length for data
    by calling getMaxDataLength().`
`    The array must contain amountOfIndexes entries.
`
