### ISSUE TITLE
Troubles using the ATtiny3217

### ISSUE THREAD

**Issue by avandalen** [PRosenb/EEPROMWearLevel#8]
Dear Pete
I have troubles using the ATtiny3217
https://github.com/SpenceKonde/megaTinyCore

The error is:
'EECR' was not declared in this scope

Note that the standard Arduino library EEPROM.h still works fine on the ATtiny3217, see this sketch:

```
#include <EEPROM.h>  
void setup() 
{ Serial.begin(9600);
  while(!Serial);
  float f = 123.456f;  
  int eeAddress = 0;   
  EEPROM.put(eeAddress, f);
  EEPROM.get(eeAddress, f);
  Serial.println(f, 3);   
}
void loop() 
{
}
```

So, I think it is not a big compatiblity issue.

I have looked for a solution, but I don’t have enough knowledge of the Arduino platform. 
Maybe you can talk to Spence Konde what to do.

**Comment by PRosenb** [comment]
Hi @avandalen,
thanks for your report.
I created a [Ticket](https://github.com/SpenceKonde/megaTinyCore/issues/156) at `metaTinyCore` to add the missing `EEPROM` related constants.

**Comment by SpenceKonde** [comment]
This has nothing to do with the core, those are hardware registers - they do not exist on megaavr parts as the megaavr NVMCTRL module works very differently from how you write to EEPROM on classic AVRs.

**Comment by avandalen** [comment]
Dear Pete

Thank you very much, it works now with the ATtiny3217.
I use your library for an ebike battery fuel gauge with the LTC2944.
